### ISSUE TITLE
Realistic Dummy Quizzes Available

### ISSUE THREAD

**Issue by cashewpillar** [xtian18/kweeznuts#4]
**To-Dos:**
- [x] Fetch updates, checkout the branch `realistic-dummy-quiz`
- [x] Re-generate initial data `python main.py initial-data`
- [x] Check if works correctly, raise issues at https://github.com/Iionsroar/inquizitor/pull/36
- [x] Toggle remaining task at https://github.com/Iionsroar/inquizitor/pull/36 when done

\* **Note:** Collaborators can toggle the checkboxes above for progress monitoring
